# Generated by Django 6.1.1 on 2026-10-01 08:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_satisayarlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('ad', models.CharField(max_length=80, unique=True, verbose_name='kategori')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='kısa ad')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('gorsel', models.ImageField(blank=True, upload_to='kategori/', verbose_name='görsel')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'kategori',
                'verbose_name_plural': 'kategoriler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('ad', models.CharField(max_length=140, verbose_name='ürün adı')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='kısa ad')),
                ('aciklama', models.TextField(blank=True, help_text='Ürün kartında görünür. Nereden geldiği, nasıl saklanacağı.', verbose_name='açıklama')),
                ('gorsel', models.ImageField(blank=True, upload_to='urun/', verbose_name='görsel')),
                ('birim', models.CharField(choices=[('kg', 'Kilogram'), ('adet', 'Adet'), ('demet', 'Demet'), ('paket', 'Paket'), ('kavanoz', 'Kavanoz'), ('sise', 'Şişe'), ('kutu', 'Kutu')], default='kg', max_length=10, verbose_name='birim')),
                ('tartili_mi', models.BooleanField(default=True, help_text='İşaretliyse sepette provizyon alınır, kesin tutar tartımdan sonra çekilir.', verbose_name='tartılı ürün')),
                ('satis_adimi', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Birim cinsinden en küçük artırma miktarı. Kilogramda 0,500 = 500 g.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='satış adımı')),
                ('ambalaj_bilgisi', models.CharField(blank=True, help_text='Ambalajlı üründe içindekinin miktarı. Örnek: 850 g, 1 L.', max_length=40, verbose_name='ambalaj')),
                ('yerel_satis', models.BooleanField(default=True, help_text='Mahalle teslimatında satılır.', verbose_name='yerel teslimat')),
                ('kargo_satis', models.BooleanField(default=False, help_text="Kargoyla tüm Türkiye'ye gönderilir. Dört şart birden sağlanmalı — aşağıdaki denetim bunu kontrol eder.", verbose_name='kargo')),
                ('kurumsal_satis', models.BooleanField(default=True, verbose_name='kurumsal (B2B)')),
                ('abonelige_uygun', models.BooleanField(default=False, help_text='Düzenli, tekrarlayan siparişe açılabilir mi. (Abonelik modülü sonra gelecek.)', verbose_name='aboneliğe uygun')),
                ('raf_omru_gun', models.PositiveIntegerField(blank=True, help_text='Uygun koşulda kaç gün dayanır. Kargo kararının dayanağı.', null=True, verbose_name='raf ömrü (gün)')),
                ('soguk_zincir', models.BooleanField(default=False, help_text="0–4 °C'de taşınmalı. Paketleme ve kurye ekranında uyarı çıkar.", verbose_name='soğuk zincir gerekir')),
                ('mevsim', models.CharField(blank=True, help_text='Örnek: Haziran–Ekim, Tüm yıl.', max_length=60, verbose_name='mevsim')),
                ('uyari_metni', models.CharField(blank=True, help_text='Ürün kartında ve etikette görünür. Örnek: Kullanmadan önce yıkayınız.', max_length=200, verbose_name='uyarı metni')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('aktif', models.BooleanField(default=True, help_text='Kapalıysa hiçbir mağazada görünmez.', verbose_name='aktif')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urunler', to='katalog.kategori', verbose_name='kategori')),
            ],
            options={
                'verbose_name': 'ürün',
                'verbose_name_plural': 'ürünler',
                'ordering': ['kategori__sira', 'sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='MagazaUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, help_text='Birim başına satış fiyatı. Boşken ürün satışa açılamaz.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='fiyat (₺)')),
                ('eski_fiyat', models.DecimalField(blank=True, decimal_places=2, help_text='Doluysa üstü çizili gösterilir. İndirim için.', max_digits=10, null=True, verbose_name='eski fiyat (₺)')),
                ('durum', models.CharField(choices=[('satista', 'Satışta'), ('tukendi', 'Tükendi'), ('mevsim_disi', 'Mevsim dışı')], default='satista', max_length=12, verbose_name='durum')),
                ('gunluk_limit', models.PositiveIntegerField(blank=True, help_text='Bir teslim gününde en fazla kaç birim satılsın. Boşsa sınırsız.', null=True, verbose_name='günlük satış limiti')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('aktif', models.BooleanField(default=False, help_text='Fiyat girilmeden açılamaz.', verbose_name='satışta')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='core.magaza', verbose_name='mağaza')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magaza_kayitlari', to='katalog.urun', verbose_name='ürün')),
            ],
            options={
                'verbose_name': 'mağaza ürünü',
                'verbose_name_plural': 'mağaza ürünleri',
                'ordering': ['magaza__ad', 'urun__kategori__sira', 'sira', 'urun__ad'],
                'unique_together': {('magaza', 'urun')},
            },
        ),
    ]
