# Generated by Django 6.1.1 on 2026-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_birim_tablosu_stok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stokhareketi',
            name='tur',
            field=models.CharField(choices=[('mal_kabul', 'Mal kabul'), ('fire', 'Fire'), ('sayim', 'Sayım düzeltmesi'), ('satis', 'Satış'), ('tarti_farki', 'Tartı farkı'), ('iade', 'İade'), ('takip_kapatildi', 'Takip kapatıldı')], max_length=16, verbose_name='tür'),
        ),
    ]
