# Generated by Django 6.1.1 on 2026-09-30 20:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=40, unique=True, verbose_name='il')),
                ('slug', models.SlugField(unique=True, verbose_name='kısa ad')),
                ('plaka', models.PositiveSmallIntegerField(unique=True, verbose_name='plaka kodu')),
            ],
            options={
                'verbose_name': 'il',
                'verbose_name_plural': 'iller',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='IlgiKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('eposta', models.EmailField(max_length=254, verbose_name='e-posta')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('mahalle_adi', models.CharField(blank=True, help_text='Ziyaretçinin yazdığı mahalle adı.', max_length=120, verbose_name='mahalle')),
                ('kaynak', models.CharField(blank=True, help_text='Örnek: instagram, tanıdık, arama', max_length=60, verbose_name='kaynak')),
                ('haber_verildi', models.BooleanField(default=False, verbose_name='haber verildi')),
            ],
            options={
                'verbose_name': 'ilgi kaydı',
                'verbose_name_plural': 'ilgi kayıtları',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=60, verbose_name='ilçe')),
                ('slug', models.SlugField(max_length=70, verbose_name='kısa ad')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='core.il', verbose_name='il')),
            ],
            options={
                'verbose_name': 'ilçe',
                'verbose_name_plural': 'ilçeler',
                'ordering': ['il__ad', 'ad'],
                'unique_together': {('il', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Magaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('ad', models.CharField(help_text='Örnek: Bostanhane Beyşehir', max_length=120, verbose_name='mağaza adı')),
                ('slug', models.SlugField(help_text='Adreste görünecek hali. Örnek: beysehir', max_length=140, unique=True, verbose_name='kısa ad')),
                ('adres', models.TextField(blank=True, verbose_name='açık adres')),
                ('enlem', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='enlem')),
                ('boylam', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='boylam')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='e-posta')),
                ('aktif', models.BooleanField(default=True, help_text='Kapalıysa bu mağaza sipariş almaz.', verbose_name='aktif')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazalar', to='core.il', verbose_name='il')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazalar', to='core.ilce', verbose_name='ilçe')),
            ],
            options={
                'verbose_name': 'mağaza',
                'verbose_name_plural': 'mağazalar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='mahalle')),
                ('slug', models.SlugField(max_length=140, verbose_name='kısa ad')),
                ('tip', models.CharField(choices=[('merkez', 'Merkez mahallesi'), ('kirsal', 'Köy kökenli mahalle')], default='merkez', max_length=10, verbose_name='tip')),
                ('posta_kodu', models.CharField(blank=True, max_length=5, verbose_name='posta kodu')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahalleler', to='core.ilce', verbose_name='ilçe')),
            ],
            options={
                'verbose_name': 'mahalle',
                'verbose_name_plural': 'mahalleler',
                'ordering': ['ilce__il__ad', 'ilce__ad', 'ad'],
                'unique_together': {('ilce', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HizmetMahallesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('gunluk_kapasite', models.PositiveIntegerField(default=40, help_text='Bir teslim gününde kaç siparişe kadar alınabilir.', verbose_name='günlük teslimat kapasitesi')),
                ('sira', models.PositiveIntegerField(default=0, help_text='Listelerde görünme sırası.', verbose_name='sıra')),
                ('aktif', models.BooleanField(default=True, help_text='Kapalıysa bu mahallede yerel teslimat görünmez.', verbose_name='aktif')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hizmet_mahalleleri', to='core.magaza', verbose_name='mağaza')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hizmet_kayitlari', to='core.mahalle', verbose_name='mahalle')),
            ],
            options={
                'verbose_name': 'hizmet verilen mahalle',
                'verbose_name_plural': 'hizmet verilen mahalleler',
                'ordering': ['magaza__ad', 'sira', 'mahalle__ad'],
                'unique_together': {('magaza', 'mahalle')},
            },
        ),
        migrations.CreateModel(
            name='HaftalikTeslimGunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('gun', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='teslim günü')),
                ('teslim_baslangic', models.TimeField(default=datetime.time(9, 0), verbose_name='teslimat başlangıç')),
                ('teslim_bitis', models.TimeField(default=datetime.time(18, 0), verbose_name='teslimat bitiş')),
                ('kesim_gun_farki', models.PositiveSmallIntegerField(default=1, help_text='1 = teslimattan bir gün önce.', verbose_name='kesim kaç gün önce')),
                ('kesim_saati', models.TimeField(default=datetime.time(18, 0), help_text='Bu saatten sonra sipariş alınmaz.', verbose_name='kesim saati')),
                ('kapasite', models.PositiveIntegerField(blank=True, help_text='Boş bırakılırsa mahallenin günlük kapasitesi kullanılır.', null=True, verbose_name='kapasite')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('hizmet_mahallesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haftalik_gunler', to='core.hizmetmahallesi', verbose_name='hizmet verilen mahalle')),
            ],
            options={
                'verbose_name': 'haftalık teslim günü',
                'verbose_name_plural': 'haftalık teslim günleri',
                'ordering': ['hizmet_mahallesi', 'gun'],
                'unique_together': {('hizmet_mahallesi', 'gun')},
            },
        ),
        migrations.CreateModel(
            name='TeslimTakvimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('tarih', models.DateField(verbose_name='teslim tarihi')),
                ('kesim_zamani', models.DateTimeField(verbose_name='kesim zamanı')),
                ('kapasite', models.PositiveIntegerField(default=40, verbose_name='kapasite')),
                ('durum', models.CharField(choices=[('acik', 'Açık'), ('kesildi', 'Kesildi'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='acik', max_length=12, verbose_name='durum')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('hizmet_mahallesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takvim', to='core.hizmetmahallesi', verbose_name='hizmet verilen mahalle')),
            ],
            options={
                'verbose_name': 'teslim takvimi',
                'verbose_name_plural': 'teslim takvimi',
                'ordering': ['tarih', 'hizmet_mahallesi'],
                'unique_together': {('hizmet_mahallesi', 'tarih')},
            },
        ),
    ]
