# Generated by Django 6.1.1 on 2026-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlgiKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('eposta', models.EmailField(max_length=254, verbose_name='e-posta')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('mahalle_adi', models.CharField(blank=True, help_text='Ziyaretçinin yazdığı mahalle adı.', max_length=120, verbose_name='mahalle')),
                ('kaynak', models.CharField(blank=True, help_text='Örnek: instagram, tanıdık, arama', max_length=60, verbose_name='kaynak')),
                ('haber_verildi', models.BooleanField(default=False, verbose_name='haber verildi')),
            ],
            options={
                'verbose_name': 'ilgi kaydı',
                'verbose_name_plural': 'ilgi kayıtları',
                'ordering': ['-olusturuldu'],
            },
        ),
    ]
