# Generated by Django 6.1.1 on 2026-10-01 08:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('min_sepet_tutari', models.DecimalField(decimal_places=2, help_text='Bu tutarın altındaki sepetle sipariş verilemez. 0 yazarsanız sınır kalkar.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='minimum sepet tutarı (₺)')),
                ('teslimat_ucreti', models.DecimalField(decimal_places=2, help_text='Her siparişe eklenir. 0 yazarsanız teslimat her zaman ücretsiz olur.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='teslimat ücreti (₺)')),
                ('ucretsiz_teslimat_esigi', models.DecimalField(blank=True, decimal_places=2, help_text='Bu tutarın üstündeki siparişte teslimat ücreti alınmaz. Boş bırakırsanız ücretsiz teslimat hiç olmaz.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='ücretsiz teslimat eşiği (₺)')),
                ('provizyon_tampon_orani', models.DecimalField(decimal_places=3, help_text='Tartılı üründe karttan bloke edilecek fazlalık. 0,150 = %15. Tartı tahminden fazla çıkarsa bu pay işe yarar.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='provizyon tamponu')),
                ('otomatik_teslim_onayi_saat', models.PositiveSmallIntegerField(default=24, help_text='Üye "eksiksiz teslim aldım" demezse kaç saat sonra onaylanmış sayılır.', verbose_name='otomatik teslim onayı (saat)')),
                ('talep_acma_suresi_saat', models.PositiveSmallIntegerField(default=24, help_text='Teslimden sonra kaç saat içinde iade veya şikâyet açılabilir.', verbose_name='talep açma süresi (saat)')),
                ('magaza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satis_ayarlari', to='core.magaza', verbose_name='mağaza')),
            ],
            options={
                'verbose_name': 'satış ayarları',
                'verbose_name_plural': 'satış ayarları',
                'ordering': ['magaza__ad'],
            },
        ),
    ]
