# Generated by Django 6.1.1 on 2026-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_satisayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisayarlari',
            name='vitrin_modu',
            field=models.CharField(choices=[('kapali', 'Kapalı — yalnızca yakında sayfası'), ('test', 'Test — vitrin yalnızca giriş yapanlara açık'), ('acik', 'Açık — herkese satış')], default='test', help_text="Sanal POS ve yasal metinler tamamlanana kadar TEST'te kalmalı. Test modunda verilen siparişler deneme sayılır ve raporlara girmez.", max_length=10, verbose_name='vitrin modu'),
        ),
    ]
