# Generated by Django 6.1.1 on 2026-10-01 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_satisayarlari_vitrin_modu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ilgikaydi',
            name='ilce',
            field=models.ForeignKey(blank=True, help_text='Hangi ilçeye talep var. Listeyi buna göre süzüyoruz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilgi_kayitlari', to='core.ilce', verbose_name='ilçe'),
        ),
        migrations.AddField(
            model_name='ilgikaydi',
            name='uye',
            field=models.ForeignKey(blank=True, help_text='Kayıt bir üyeden geldiyse. Ziyaretçide boş.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilgi_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='üye'),
        ),
        migrations.AlterField(
            model_name='ilgikaydi',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-posta'),
        ),
        migrations.AlterField(
            model_name='ilgikaydi',
            name='kaynak',
            field=models.CharField(blank=True, help_text='Örnek: instagram, tanıdık, arama, adres formu', max_length=60, verbose_name='kaynak'),
        ),
        migrations.AlterField(
            model_name='ilgikaydi',
            name='mahalle_adi',
            field=models.CharField(blank=True, help_text='Kişinin yazdığı mahalle adı.', max_length=120, verbose_name='mahalle'),
        ),
    ]
