# Generated by Django 6.1.1 on 2026-10-02 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ilgikaydi_ilce_ilgikaydi_uye_alter_ilgikaydi_eposta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teslimtakvimi',
            name='kurye',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa bu rotayı mağazanın bütün kuryeleri görür.', limit_choices_to={'rol': 'kurye'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotalari', to=settings.AUTH_USER_MODEL, verbose_name='kurye'),
        ),
    ]
