# Generated by Django 6.1.1 on 2026-10-03 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teslimtakvimi_kurye'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilgikaydi',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=120, verbose_name='ad soyad'),
        ),
        migrations.AddField(
            model_name='ilgikaydi',
            name='mahalle',
            field=models.ForeignKey(blank=True, help_text='Mahalle listede varsa seçilir; yoksa boş kalır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilgi_kayitlari', to='core.mahalle', verbose_name='mahalle (resmî)'),
        ),
        migrations.AddField(
            model_name='mahalle',
            name='nufus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nüfus'),
        ),
        migrations.AddField(
            model_name='mahalle',
            name='nufus_kaynagi',
            field=models.CharField(blank=True, help_text='Örnek: TÜİK ADNKS 2023', max_length=120, verbose_name='nüfus kaynağı'),
        ),
        migrations.AddField(
            model_name='mahalle',
            name='nufus_yili',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nüfus yılı'),
        ),
        migrations.AlterField(
            model_name='ilgikaydi',
            name='mahalle_adi',
            field=models.CharField(blank=True, help_text='Kişinin yazdığı mahalle adı. Resmî mahalle seçilemediğinde buraya bakılır.', max_length=120, verbose_name='mahalle (yazılan)'),
        ),
    ]
