# Generated by Django 6.1.1 on 2026-10-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siparis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdemeIslemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('tur', models.CharField(choices=[('provizyon', 'Provizyon (bloke)'), ('cekim', 'Çekim'), ('iade', 'İade'), ('bloke_coz', 'Bloke çözüldü')], max_length=12, verbose_name='işlem')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('basarili', 'Başarılı'), ('basarisiz', 'Başarısız')], default='bekliyor', max_length=10, verbose_name='durum')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tutar')),
                ('saglayici', models.CharField(max_length=20, verbose_name='sağlayıcı')),
                ('saglayici_islem_no', models.CharField(blank=True, help_text='Bankayla konuşurken bu numara kullanılır.', max_length=100, verbose_name='sağlayıcı işlem no')),
                ('istek_anahtari', models.CharField(max_length=80, unique=True, verbose_name='istek anahtarı')),
                ('hata_kodu', models.CharField(blank=True, max_length=40, verbose_name='hata kodu')),
                ('hata_mesaji', models.CharField(blank=True, max_length=300, verbose_name='hata mesajı')),
                ('yanit', models.JSONField(blank=True, default=dict, help_text='Kart alanları temizlenmiş ham yanıt.', verbose_name='sağlayıcı yanıtı')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='açıklama')),
                ('kaynak_islem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bagli_islemler', to='odeme.odemeislemi', verbose_name='kaynak işlem')),
                ('kullanici', models.ForeignKey(blank=True, help_text='Kendiliğinden çalışan işlemlerde boştur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odeme_islemleri', to=settings.AUTH_USER_MODEL, verbose_name='işlemi yapan')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odeme_islemleri', to='siparis.siparis', verbose_name='sipariş')),
            ],
            options={
                'verbose_name': 'ödeme işlemi',
                'verbose_name_plural': 'ödeme işlemleri',
                'ordering': ['-olusturuldu'],
                'indexes': [models.Index(fields=['siparis', 'tur', 'durum'], name='odeme_odeme_siparis_d23001_idx')],
            },
        ),
    ]
