# Generated by Django 6.1.1 on 2026-10-01 12:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_satisayarlari_vitrin_modu'),
        ('hesaplar', '0001_initial'),
        ('katalog', '0003_alter_stokhareketi_tur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('oturum_anahtari', models.CharField(blank=True, help_text='Giriş yapmamış ziyaretçinin sepeti.', max_length=40, verbose_name='oturum anahtarı')),
                ('adres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepetler', to='hesaplar.adres', verbose_name='teslimat adresi')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepetler', to='core.magaza', verbose_name='mağaza')),
                ('teslim_takvimi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepetler', to='core.teslimtakvimi', verbose_name='teslim günü')),
                ('uye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sepetler', to=settings.AUTH_USER_MODEL, verbose_name='üye')),
            ],
            options={
                'verbose_name': 'sepet',
                'verbose_name_plural': 'sepetler',
                'ordering': ['-guncellendi'],
            },
        ),
        migrations.CreateModel(
            name='SepetKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('miktar', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='miktar')),
                ('magaza_urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sepet_kalemleri', to='katalog.magazaurun', verbose_name='ürün')),
                ('sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='siparis.sepet', verbose_name='sepet')),
            ],
            options={
                'verbose_name': 'sepet kalemi',
                'verbose_name_plural': 'sepet kalemleri',
                'ordering': ['magaza_urun__urun__kategori__sira', 'magaza_urun__urun__ad'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('numara', models.CharField(editable=False, max_length=20, unique=True, verbose_name='sipariş no')),
                ('kanal', models.CharField(choices=[('yerel', 'Yerel teslimat'), ('kargo', 'Kargo'), ('kurumsal', 'Kurumsal')], default='yerel', max_length=10, verbose_name='kanal')),
                ('teslim_ad_soyad', models.CharField(max_length=120, verbose_name='teslim alacak kişi')),
                ('teslim_telefon', models.CharField(max_length=10, verbose_name='teslimat telefonu')),
                ('teslim_acik_adres', models.TextField(verbose_name='açık adres')),
                ('teslim_mahalle', models.CharField(max_length=120, verbose_name='mahalle')),
                ('teslim_ilce', models.CharField(max_length=60, verbose_name='ilçe')),
                ('teslim_il', models.CharField(max_length=40, verbose_name='il')),
                ('teslim_tarif', models.CharField(blank=True, max_length=200, verbose_name='kuryeye not')),
                ('teslim_enlem', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='enlem')),
                ('teslim_boylam', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='boylam')),
                ('ara_toplam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ara toplam')),
                ('teslimat_ucreti', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='teslimat ücreti')),
                ('toplam', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='toplam')),
                ('provizyon_tutari', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='bloke edilen')),
                ('cekilen_tutar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='çekilen')),
                ('durum', models.CharField(choices=[('alindi', 'Alındı'), ('kesildi', 'Kesildi'), ('hazirlaniyor', 'Hazırlanıyor'), ('yolda', 'Yolda'), ('teslim_edildi', 'Teslim edildi'), ('iptal', 'İptal')], default='alindi', max_length=15, verbose_name='durum')),
                ('odeme_durumu', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('provizyon', 'Provizyon alındı'), ('cekildi', 'Çekildi'), ('kismi_iade', 'Kısmi iade'), ('iade', 'İade edildi'), ('basarisiz', 'Başarısız')], default='bekliyor', max_length=12, verbose_name='ödeme')),
                ('musteri_notu', models.CharField(blank=True, max_length=300, verbose_name='müşteri notu')),
                ('ic_not', models.TextField(blank=True, help_text='Müşteriye görünmez.', verbose_name='iç not')),
                ('test_siparisi', models.BooleanField(default=False, help_text='Vitrin test modundayken verilen sipariş. Raporlarda sayılmaz.', verbose_name='deneme siparişi')),
                ('kesildi_zamani', models.DateTimeField(blank=True, null=True, verbose_name='kesim zamanı')),
                ('hazirlandi_zamani', models.DateTimeField(blank=True, null=True, verbose_name='hazırlanma zamanı')),
                ('teslim_zamani', models.DateTimeField(blank=True, null=True, verbose_name='teslim zamanı')),
                ('onay_zamani', models.DateTimeField(blank=True, null=True, verbose_name='üye onayı')),
                ('magaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siparisler', to='core.magaza', verbose_name='mağaza')),
                ('teslim_takvimi', models.ForeignKey(blank=True, help_text='Kargo siparişinde boştur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siparisler', to='core.teslimtakvimi', verbose_name='teslim günü')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siparisler', to=settings.AUTH_USER_MODEL, verbose_name='üye')),
            ],
            options={
                'verbose_name': 'sipariş',
                'verbose_name_plural': 'siparişler',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('urun_adi', models.CharField(max_length=140, verbose_name='ürün')),
                ('birim_adi', models.CharField(max_length=12, verbose_name='birim')),
                ('tartili_mi', models.BooleanField(default=False, verbose_name='tartılı')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='birim fiyat')),
                ('siparis_miktari', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='sipariş miktarı')),
                ('teslim_miktari', models.DecimalField(blank=True, decimal_places=3, help_text='Tartımdan sonra girilir. Ürün bulunamadıysa 0 yazılır.', max_digits=10, null=True, verbose_name='teslim miktarı')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('hazir', 'Hazırlandı'), ('bulunamadi', 'Bulunamadı')], default='bekliyor', max_length=12, verbose_name='durum')),
                ('not_metni', models.CharField(blank=True, max_length=200, verbose_name='not')),
                ('magaza_urun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siparis_kalemleri', to='katalog.magazaurun', verbose_name='ürün')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='siparis.siparis', verbose_name='sipariş')),
            ],
            options={
                'verbose_name': 'sipariş kalemi',
                'verbose_name_plural': 'sipariş kalemleri',
                'ordering': ['urun_adi'],
            },
        ),
        migrations.AddConstraint(
            model_name='sepet',
            constraint=models.UniqueConstraint(condition=models.Q(('uye__isnull', False)), fields=('uye', 'magaza'), name='uye_basina_tek_sepet'),
        ),
        migrations.AddConstraint(
            model_name='sepet',
            constraint=models.UniqueConstraint(condition=models.Q(('uye__isnull', True)), fields=('oturum_anahtari', 'magaza'), name='oturum_basina_tek_sepet'),
        ),
        migrations.AlterUniqueTogether(
            name='sepetkalemi',
            unique_together={('sepet', 'magaza_urun')},
        ),
        migrations.AddIndex(
            model_name='siparis',
            index=models.Index(fields=['magaza', 'durum'], name='siparis_sip_magaza__11e1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='siparis',
            index=models.Index(fields=['teslim_takvimi', 'durum'], name='siparis_sip_teslim__431076_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sipariskalemi',
            unique_together={('siparis', 'magaza_urun')},
        ),
    ]
