# Generated by Django 6.1.1 on 2026-09-30 20:15

import django.db.models.deletion
import hesaplar.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('telefon', models.CharField(help_text='10 hane, başında sıfır olmadan. Örnek: 5321112233', max_length=10, unique=True, validators=[hesaplar.models.telefon_dogrula], verbose_name='telefon')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='ad soyad')),
                ('eposta', models.EmailField(blank=True, help_text='Zorunlu değil. Fatura ve bildirim için kullanılır.', max_length=254, verbose_name='e-posta')),
                ('rol', models.CharField(choices=[('super_admin', 'Süper Admin'), ('magaza_yoneticisi', 'Mağaza Yöneticisi'), ('paketleme', 'Paketleme Elemanı'), ('kurye', 'Kurye'), ('uye', 'Üye')], default='uye', max_length=20, verbose_name='rol')),
                ('telefon_dogrulandi', models.BooleanField(default=False, help_text='SMS ile doğrulandıysa işaretlidir.', verbose_name='telefon doğrulandı')),
                ('kvkk_onayi', models.DateTimeField(blank=True, help_text='Üyelik sırasında aydınlatma metnini onayladığı an.', null=True, verbose_name='KVKK onay zamanı')),
                ('duyuru_izni', models.BooleanField(default=False, help_text='Kapalıysa tanıtım mesajı gönderilmez. Sipariş bildirimleri bundan bağımsızdır.', verbose_name='kampanya bildirimi izni')),
                ('is_active', models.BooleanField(default=True, help_text='Kapalıysa bu kişi sisteme giriş yapamaz. Hesabı silmek yerine bunu kapatın.', verbose_name='aktif')),
                ('is_staff', models.BooleanField(default=False, help_text='Rol seçimine göre otomatik ayarlanır; elle değiştirmeniz gerekmez.', verbose_name='yönetim paneline girebilir')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('magaza', models.ForeignKey(blank=True, help_text='Mağaza yöneticisi, paketleme ve kurye için zorunlu. Süper admin ve üyede boş kalır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personel', to='core.magaza', verbose_name='bağlı mağaza')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'kullanıcı',
                'verbose_name_plural': 'kullanıcılar',
                'ordering': ['ad_soyad'],
            },
            managers=[
                ('objects', hesaplar.models.KullaniciYoneticisi()),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('baslik', models.CharField(default='Ev', help_text='Örnek: Ev, İş, Annem', max_length=40, verbose_name='adres başlığı')),
                ('acik_adres', models.TextField(help_text='Cadde, sokak, apartman adı.', verbose_name='açık adres')),
                ('bina_no', models.CharField(blank=True, max_length=10, verbose_name='bina no')),
                ('kat', models.CharField(blank=True, max_length=10, verbose_name='kat')),
                ('daire', models.CharField(blank=True, max_length=10, verbose_name='daire')),
                ('teslim_alacak', models.CharField(blank=True, help_text='Boşsa üyenin kendi adı kullanılır.', max_length=120, verbose_name='teslim alacak kişi')),
                ('teslim_telefonu', models.CharField(blank=True, help_text='Boşsa üyenin telefonu kullanılır.', max_length=10, verbose_name='teslimat telefonu')),
                ('tarif', models.CharField(blank=True, help_text='Örnek: Zil çalışmıyor, arayın. Bakkalın üstü.', max_length=200, verbose_name='kuryeye not')),
                ('enlem', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='enlem')),
                ('boylam', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='boylam')),
                ('varsayilan', models.BooleanField(default=False, help_text='Sepette önce bu adres seçili gelir.', verbose_name='varsayılan adres')),
                ('aktif', models.BooleanField(default=True, help_text='Silmek yerine kapatılır; eski siparişlerin adresi bozulmasın.', verbose_name='aktif')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adresler', to='core.mahalle', verbose_name='mahalle')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresler', to=settings.AUTH_USER_MODEL, verbose_name='üye')),
            ],
            options={
                'verbose_name': 'adres',
                'verbose_name_plural': 'adresler',
                'ordering': ['-varsayilan', 'baslik'],
                'unique_together': {('uye', 'baslik')},
            },
        ),
    ]
