# Generated by Django 6.1.1 on 2026-10-03 10:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siparis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('tur', models.CharField(choices=[('kusurlu', 'Ürün kusurlu / bozuk'), ('eksik', 'Ürün eksik ya da hiç gelmedi'), ('yanlis', 'Yanlış ürün geldi'), ('diger', 'Diğer')], default='kusurlu', max_length=10, verbose_name='sorun')),
                ('aciklama', models.TextField(max_length=1000, verbose_name='müşterinin açıklaması')),
                ('durum', models.CharField(choices=[('acik', 'Açık — mağaza bakacak'), ('inceleniyor', 'İnceleniyor'), ('kabul', 'Kabul edildi — iade yapıldı'), ('kismi', 'Kısmen kabul edildi'), ('red', 'Reddedildi')], default='acik', max_length=12, verbose_name='durum')),
                ('karar_notu', models.TextField(blank=True, help_text='Müşteriye gösterilir. Kararın sebebini yazın.', max_length=1000, verbose_name='mağazanın kararı')),
                ('karar_zamani', models.DateTimeField(blank=True, null=True, verbose_name='karar zamanı')),
                ('iade_tutari', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='iade edilen')),
                ('kalem', models.ForeignKey(blank=True, help_text='Boşsa sorun siparişin tamamıyla ilgili.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='siparis.sipariskalemi', verbose_name='ürün')),
                ('karar_veren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdigi_kararlar', to=settings.AUTH_USER_MODEL, verbose_name='kararı veren')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talepler', to='siparis.siparis', verbose_name='sipariş')),
            ],
            options={
                'verbose_name': 'talep',
                'verbose_name_plural': 'talepler',
                'ordering': ['-olusturuldu'],
            },
        ),
        migrations.CreateModel(
            name='TalepGorseli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturuldu', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('gorsel', models.ImageField(upload_to='talep/', verbose_name='fotoğraf')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='sıra')),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorseller', to='talep.talep', verbose_name='talep')),
            ],
            options={
                'verbose_name': 'talep fotoğrafı',
                'verbose_name_plural': 'talep fotoğrafları',
                'ordering': ['sira', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='talep',
            index=models.Index(fields=['siparis', 'durum'], name='talep_talep_siparis_390666_idx'),
        ),
    ]
