# Generated by Django 6.1.1 on 2026-10-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odeme', '0001_initial'),
        ('talep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talep',
            name='odeme_islemi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='odeme.odemeislemi', verbose_name='iade işlemi'),
        ),
    ]
